[tool.poetry]
name = "bank-it"
version = "0.1.0"
description = ""
authors = ["etaulan@mail.ru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"
pytest = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
